### ISSUE TITLE
Connect all mods sources as submodule

### ISSUE THREAD

**Issue by bell07** [minetest-whynot/whynot-builder#1]
All source games, modpacks and mods needs to be connected as submodule to this repository
- [x] #2
- [x] ambience/ambience
- [x] ambience/lightning
- [x] ambience/under_sky
- [x] ambience/weather_pack
- [x] decor/abriglass
- [x] decor/basic_materials
- [x] decor/campfire
- [x] decor/curtain
- [x] decor/dice2
- [x] decor/flower_pot
- [x] decor/heads
- [x] decor/laptop
- [x] decor/mtg_plus
- [x] decor/myroofs
- [x] decor/plasticbox
- [x] decor/princess
- [x] decor/realchess
- [x] decor/slats
- [x] decor/ts_furniture
- [x] decor/unifieddyes
- [x] flight
- [x] flora_ores/farming
- [x] flora_ores/mese_crystals
- [x] food/canned_food
- [x] food/food_sweet
- [x] food_modpack
- [x] food/mtfoods
- [x] food/pie
- [x] food/waffles
- [x] #3
- [x] #4
- [x] libs/craftguide_reveal
- [x] libs/doc
- [x] libs/doc_basics
- [x] libs/doc_items
- [x] libs/doc_minetest_game
- [x] libs/doc_reveal_chest
- [x] libs/intllib
- [x] libs/whynot_compat
- [x] maidroid
- [x] mapgen/cloudlands
- [x] mapgen/maple
- [x] mapgen/meseor
- [x] mapgen/pbj_pup
- [x] mapgen/tac_nayn
- [x] mesecons
- [x] minetest_game
- [x] mobs_redo/mobs_ghost_redo
- [x] mobs_redo/mobs_monster
- [x] mobs_redo/mobs_redo
- [x] mydoors
- [x] player_api_modpack
- [x] player/awards
- [x] player/cozy
- [x] player/hbarmor
- [x] player/hbhunger
- [x] player/hbsprint
- [x] player/hudbars
- [x] player/moarmour
- [x] player/playeranim
- [x] player/show_wielded_item
- [x] player/wielded_light
- [x] smart_sfinv_modpack
- [x] tools/backpacks
- [x] tools/bonemeal
- [x] tools/boost_cart
- [x] tools/ccompass
- [x] tools/compost
- [x] tools/engrave
- [x] tools/handholds
- [x] tools/helicopter
- [x] tools/hopper
- [x] tools/jumping
- [x] tools/orbs_of_time
- [x] tools/rainbowswords
- [x] tools/subspacewalker
- [x] tools/toolranks
- [x] tools/trash_can
- [x] tools/woodcutting

**Comment by Lazerbeak12345** [comment]
Wow great work on this.

**Comment by bell07** [comment]
All done ;-)
